artist: "opac"
album: "PAUSE"
cover: "./example_cover.jpg"
colors:
  main: "#ffffff"
  primary: "#DAA520"
  secondary: "#4A9EFF"
tracks:
  - name: "Banm Kalou Banm"
    artists: ["xoticboii"]
    audio: "./example_track.wav"
  - name: "Ram√®ne-Le"
    artists: ["Al'Phao X xoticboii"]
    audio: "./example_track.wav"
#background: 
#  blurBrightness: 0.6
#  blurAmount: 30
#  zoom: 10
#  color: "#ea8d46"
#hide_label: true